# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Viktor Sanca
url: https://www.viktorsanca.com

repository: vsanca/vsanca.github.io
email: viktor.sanca@epfl.ch
description: >- # this means to ignore newlines until "baseurl:"
  Viktor Sanca's personal website.
github_username: vsanca
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Viktor Sanca"
  avatar : "/assets/images/sanca-photo.jpeg"
  bio    : "PhD candidate at EPFL.\
    Interested in systems, databases, ML, and how to make them efficient and fast."
  location: "Lausanne, Switzerland :switzerland:"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://viktorsanca.com"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:viktor.sanca@epfl.ch"
    - label: "EPFL page"
      icon: "fa fa-fw fa-university"
      url: "https://people.epfl.ch/viktor.sanca/?lang=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vsanca"
    - label: "Scholar"
      icon: "ai ai-google-scholar"
      url: "http://scholar.google.com/citations?user=EruWDMwAAAAJ"
    - label: "DBLP"
      icon: "ai ai-dblp"
      url: "https://dblp.uni-trier.de/pid/288/0272.html"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "http://orcid.org/0000-0002-4799-8467"
    - label: "LinkedIn"
      icon: "fa fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/viktor-sanca"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:viktor.sanca@epfl.ch"
    - label: "LinkedIn"
      icon: "fa fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/viktor-sanca"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Analytics
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-233552951-1"
    anonymize_ip: false # default
    google_site_verification: SJyLOqfKiZVXghmDdl9vNFWZByqAZPjtP2m0z0AzkMk # your google-site-verification ID (Google Search Console)

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

atom_feed:
  hide: true
